[signing]
active = "ALWAYS"
armored = true

[deploy.maven.mavenCentral.release-deploy]
active = "RELEASE"
url = "https://central.sonatype.com/api/v1/publisher"
stagingRepositories = ["target/staging-deploy"]
applyMavenCentralRules = true

[release.github]
owner = "OpenElementsLabs"
name = "GoCardlessBankAccountClient"